### ISSUE TITLE
Time units rounding down to 0 (daily rewards, hopium, maybe more I'm forgetting)

### ISSUE THREAD

**Issue by Mazedotexe** [outpoot/rugplay#63]
![Image](https://github.com/user-attachments/assets/7d486c74-e322-4a0a-99c4-04d0af35b2ba)

![Image](https://github.com/user-attachments/assets/b4300f19-acf5-47e0-8790-b401cdf359fe)

I'll make a PR tomorrow probably but I need 😴 ok bye

**Comment by face-hh** [comment]
Fixed

**Comment by Mazedotexe** [comment]
![It seems this still happens.](https://github.com/user-attachments/assets/712030bc-90db-4cd4-b7dc-3508283cebb0)
It seems this still happens.
